// Generated by CoffeeScript 1.4.0

/*
 * Description or Responsability
 *
 * @namespace KINOUT
 * @class Router
 *
 * @author Javier Jimenez Villar <javi@tapquo.com> || @soyjavi
*/


(function() {

  KINOUT.Router = (function(knt, undefined_) {
    var direction, _down, _index, _left, _right, _up;
    _index = {};
    direction = function(direction) {
      _index = knt.View.index();
      switch (direction) {
        case "left":
          return _left();
        case "right":
          return _right();
        case "up":
          return _up();
        case "down":
          return _down();
      }
    };
    _left = function() {
      _index.horizontal--;
      knt.View.slide(_index.horizontal, 0, false);
    };
    _right = function() {
      _index.horizontal++;
      knt.View.slide(_index.horizontal, 0);
    };
    _up = function() {
      _index.vertical--;
      knt.View.slide(_index.horizontal, _index.vertical, false);
    };
    _down = function() {
      _index.vertical++;
      knt.View.slide(_index.horizontal, _index.vertical);
    };
    return {
      direction: direction
    };
  })(KINOUT);

}).call(this);
