// Generated by CoffeeScript 1.4.0

/*
 * Description or Responsability
 *
 * @namespace KINOUT
 * @class Url
 *
 * @author Javier Jimenez Villar <javi@tapquo.com> || @soyjavi
*/


(function() {

  KINOUT.Url = (function(knt, undefined_) {
    /*
            Read the page URL (hash) to get the current
            navigational slide.
    */

    var read, write;
    read = function() {
      var bits, indexh, indexv;
      bits = window.location.hash.slice(2).split("/");
      indexh = (bits[0] ? parseInt(bits[0]) : 0);
      indexv = (bits[1] ? parseInt(bits[1]) : 0);
      knt.View.slide(indexh, indexv);
    };
    /*
            Updates the page URL (hash) to reflect the current
            navigational slide.
    */

    write = function(horizontal_idx, vertical_idx) {
      var url;
      url = "/";
      if (horizontal_idx > 0 || vertical_idx > 0) {
        url += horizontal_idx;
      }
      if (vertical_idx > 0) {
        url += "/" + vertical_idx;
      }
      window.location.hash = url;
    };
    return {
      read: read,
      write: write
    };
  })(KINOUT);

}).call(this);
